Symlink for filenames
ashwanthkumar/marathon-logger pull request #4
Opened 2016-09-16 11:25 UTC by aayushKumarJarvis

This PR is in reference to an issue which we experienced while integrating marathon-logger with **loggly**. Marathon Logger generates a rsyslog configuration file so as to pass logs to `syslog` which can be consumed by loggly. But the problem here was that length of mesos's tasks log file path in a configuration file for `rsyslog` cannot be more than `200` characters 😢 . 

We at [Indix](www.indix.com) fixed this issue by creating a symlink for the absolute path for mesos logs for tasks running on a particular machine. This made our life easy here for deploying marathon-logger for all our mesos-marathon based systems. 

cc : @ashwanthkumar

2016-09-16 11:27 UTC, aayushKumarJarvis commented
@brewkode, there were a few fixes in the PR which are now done.

2016-09-16 11:33 UTC, ashwanthkumar commented on glide.lock
> +  version: 2df174808ee097f90d259e432cc04442cf60be21
@aayushKumarJarvis if this update is not required as part of this change, please revert this.

2016-09-16 11:34 UTC, ashwanthkumar commented on rsyslog-logger.go
> +		File="{{ .WorkDir }}/{{ .FileName }}"
@aayushKumarJarvis We always seem to have some space vs tab issue in here. Can you please fix this?

2016-09-16 11:35 UTC, ashwanthkumar commented on rsyslog-logger.go
> +	err = os.Symlink(taskInfo.CWD, fmt.Sprintf("%s/%s", r.WorkDir, taskInfo.TaskID))
@aayushKumarJarvis Can we please extract `fmt.Sprintf("%s/%s", r.WorkDir, taskInfo.TaskID)` into a private function inside `Rsyslog` ? We're using it at another place and it's best if the whole thing is at a single place.

2016-09-16 11:36 UTC, ashwanthkumar commented on task-manager.go
> +	//		if task.Hostname == hostname {
@aayushKumarJarvis Please revert this section to the one in the master. Check the diff above.

2016-09-16 11:36 UTC, ashwanthkumar requested changes

2016-09-17 04:15 UTC, ashwanthkumar commented
@aayushKumarJarvis Made the fixes, merging this.

2016-09-17 04:15 UTC, merged